remote_theme: pages-themes/tactile@v0.2.0
plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
relative_links:
  enabled: true
  collections: true
  include:
    - CONTRIBUTING.md
    - README.md
    - LICENSE.md
